### ISSUE TITLE
Could not find property 'onesignal_jamdroid_app_id' on ProductFlavor_Decorated

### ISSUE THREAD

**Issue by Naguchennai** [ygorcesar/JamDroidFireChat#1]
Error:(16, 0) Could not find property 'onesignal_jamdroid_app_id' on ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=null, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=null, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}}.
<a href="openFile:C:\New folder\JamDroidFireChat-master\JamDroidFireChat-master\app\build.gradle">Open File</a>

 println "5138c94dfdsf-7a1e-4a68-9f22-55fb5f39a04f: ${onesignal_jamdroid_app_id}"
        println "11325517056: ${onesignal_google_jamdroid_project_number}"

**Comment by ygorcesar** [comment]
Try add in your "gradle.properties" file:

EX:
DroidJamFireChatRootUrl="https://your_app_url.firebaseio.com"
FacebookAppIdJamdroid="1111111111111111"
onesignal_jamdroid_app_id=1a1a1a11-1111-1a11-111a-1a1aaa1111a1
onesignal_google_jamdroid_project_number=111111111111

**Comment by Naguchennai** [comment]
many error can you plss update it?

**Comment by ygorcesar** [comment]
Try download this: https://github.com/ygorcesar/JamDroidFireChat/blob/master/gradle.properties
and put in root folder, and change the ID's with your ID's and Firebase App URL

**Comment by ygorcesar** [comment]
@naguchennai

**Comment by ygorcesar** [comment]
@naguchennai It's worked? :smiley:

**Comment by Naguchennai** [comment]
Yes working fine .. thank you
