### ISSUE TITLE
 Google login loading forever

### ISSUE THREAD

**Issue by Naguchennai** [ygorcesar/JamDroidFireChat#2]
I creat new app with new firebase console ..then clicked Android and added package name added SHA-1 and i enabled google signing method 

Then i copy server key from firebase google cloud message tab  added it you project build gradle.properties  firebasecloudmessagekey ..  also i renamed your package name to my package name what i gave it in firebase cloud message ,,,  i also insert google-services json ..

Finally i run project working fine .. But google login loading forever not finished and not work    What i did wrong???????? i neeed add firebase url in app? where?

**Comment by ygorcesar** [comment]
Hello Nagu, sorry for delay, you can see in your logcat if it prints some exception or crash?

**Comment by Naguchennai** [comment]
If gmail no profile photo it not work if have photo it work

photoUrl = user.getPhotoUrl().toString();    this line gave nullpoint ...

**Comment by Naguchennai** [comment]
this is error

.760 29575-29575/com.tamil.chatrooms E/UncaughtException:
java.lang.NullPointerException

at
com.tamil.chatrooms.view.activity.LoginActivity.setAuthenticatedWithOAuth(LoginActivity.java:225)

at
com.tamil.chatrooms.view.activity.LoginActivity.access$000(LoginActivity.java:49)

at
com.tamil.chatrooms.view.activity.LoginActivity$1.onAuthStateChanged(LoginActivity.java:79)

at com.google.firebase.auth.FirebaseAuth$2.run(Unknown Source)

at android.os.Handler.handleCallback(Handler.java:733)

at android.os.Handler.dispatchMessage(Handler.java:95)

at android.os.Looper.loop(Looper.java:136)

at android.app.ActivityThread.main(ActivityThread.java:5021)

at java.lang.reflect.Method.invokeNative(Native Method)

at java.lang.reflect.Method.invoke(Method.java:515)

at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)

at dalvik.system.NativeStart.main(Native Method)
