### ISSUE TITLE
FragmentChatsBinding mFragmentChatsBinding

### ISSUE THREAD

**Issue by adrianojpn** [ygorcesar/JamDroidFireChat#4]
Gostariaa de informações a respeito da implementação da Class FragmentChatsBinding mFragmentChatsBinding

**Comment by ygorcesar** [comment]
Olá Adriano blz cara, essa classe ela é gerada automaticamente pelo AnnotationProcessor do Databinding onde no layout xml é utilizado como root tag <layout>, no caso do Class FragmentChatsBinding ela é gerada em cima do layout [fragment_chats.xml](https://github.com/ygorcesar/JamDroidFirechat/blob/master/app/src/main/res/layout/fragment_chats.xml).
